### PR TITLE
chore: update dependencies

### PR DESCRIPTION
**Pull request by lino-levan**

### CODE REVIEW

**Comment by lino-levan** [comment]
@MierenManz does this look good?

**Comment by MierenManz** [comment]
Yeah j already got scared why the duff was 250 lines 😅 if the tests pass then I'll merge

**Comment by lino-levan** [comment]
I have an idea on why the tests are failing hold on.

**Comment by lino-levan** [comment]
I updated the link, and it looks like the test that was failing no longer fails, but now when I run the testing locally, I get a deno panic because of some broken pipe error. Wondering if there is a flaky test potentially somewhere?

**Comment by MierenManz** [comment]
pipes only have a 64kb buffer. So if it get's written to by the process but never read in deno it will eventually call broken pipe. It's a design limitation with the current api.

I really want to rework this fully so that it will be more flexible etc.
But that is into the future. For now I'll just merge this if the test failure is unrelated to the change

**Comment by lino-levan** [comment]
@MierenManz given that no actual code was changed, and only the dependencies were bumped, I would say this failure has nothing to do with the changes right?

**Comment by MierenManz** [comment]
I assume not so I'll just merge it

**Pull request merged**
